### ISSUE TITLE
Возникла проблема

### ISSUE THREAD

**Issue by qunn** [0x6368656174/atol-online#4]
В общем все сделал по новому ридми.
[2019-02-08 20:09:10] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 4 passed to ItQuasar\AtolOnline\AtolClient::__construct() must implement interface Psr\SimpleCache\CacheInterface, instance of Cache\Adapter\Common\CacheItem given, called in /var/www/fastuser/data/www/commenter.us/app/Http/Controllers/AtolController.php on line 142 in /var/www/fastuser/data/www/commenter.us/vendor/it-quasar/atol-online/src/AtolClient.php:46
Stack trace:
#0 /var/www/fastuser/data/www/commenter.us/app/Http/Controllers/AtolController.php(142): ItQuasar\AtolOnline\AtolClient->__construct('******', '******', '******', Object(Cache\Adapter\Common\CacheItem), NULL)
#1 /var/www/fastuser/data/www/commenter.us/app/Http/Controllers/TestController.php(28): App\Http\Controllers\AtolController->sendCheck()
#2 [internal function]: App\Http\Controllers\TestController->init()

Тоесть вызываю контроллер, где прописаны все данные по примеру, такая же кстати проблема была до обновления, вроде бы все починил сам и застряло на кеше. Вот 142 строка, где идет вызов клиента.

		$filesystemAdapter = new Local(__DIR__.'/');
		$filesystem = new Filesystem($filesystemAdapter);
		$pool = new FilesystemCachePool($filesystem);
		$cache = $pool->getItem('atol');

		// PSR-совместимый логгер (опциональный параметр)
		$logger = null;

		// Логин, пароль и код группы можно найти в "Настройках интергатора", скачиваемых с 
		// личного кабинета АТОЛ Онлайн в ноде <access>
		$login = $this->login;
		$password = $this->pass;
		$groupCode = $this->groupCode;

		// Создадим клиент
		$client = new AtolClient($login, $password, $groupCode, $cache, $logger);

Фреймворк на всякий случай, LAravel 5.4
var_dump переменной cache показывает содержимое, value почему то пусто

object(Cache\Adapter\Common\CacheItem)#297 (7) {
  ["prevTags":"Cache\Adapter\Common\CacheItem":private]=>
  array(0) {
  }
  ["tags":"Cache\Adapter\Common\CacheItem":private]=>
  array(0) {
  }
  ["callable":"Cache\Adapter\Common\CacheItem":private]=>
  object(Closure)#296 (2) {
    ["static"]=>
    array(1) {
      ["key"]=>
      string(4) "atol"
    }
    ["this"]=>
    object(Cache\Adapter\Filesystem\FilesystemCachePool)#295 (4) {
      ["filesystem":"Cache\Adapter\Filesystem\FilesystemCachePool":private]=>
      object(League\Flysystem\Filesystem)#293 (3) {
        ["adapter":protected]=>
        object(League\Flysystem\Adapter\Local)#292 (5) {
          ["pathSeparator":protected]=>
          string(1) "/"
          ["permissionMap":protected]=>
          array(2) {
            ["file"]=>
            array(2) {
              ["public"]=>
              int(420)
              ["private"]=>
              int(384)
            }
            ["dir"]=>
            array(2) {
              ["public"]=>
              int(493)
              ["private"]=>
              int(448)
            }
          }
          ["writeFlags":protected]=>
          int(2)
          ["linkHandling":"League\Flysystem\Adapter\Local":private]=>
          int(2)
          ["pathPrefix":protected]=>
          string(61) "/var/www/fastuser/data/www/commenter.us/app/Http/Controllers/"
        }
        ["plugins":protected]=>
        array(0) {
        }
        ["config":protected]=>
        object(League\Flysystem\Config)#294 (2) {
          ["settings":protected]=>
          array(0) {
          }
          ["fallback":protected]=>
          NULL
        }
      }
      ["folder":"Cache\Adapter\Filesystem\FilesystemCachePool":private]=>
      string(5) "cache"
      ["logger":"Cache\Adapter\Common\AbstractCachePool":private]=>
      NULL
      ["deferred":protected]=>
      array(0) {
      }
    }
  }
  ["key":"Cache\Adapter\Common\CacheItem":private]=>
  string(4) "atol"
  ["value":"Cache\Adapter\Common\CacheItem":private]=>
  NULL
  ["expirationTimestamp":"Cache\Adapter\Common\CacheItem":private]=>
  NULL
  ["hasValue":"Cache\Adapter\Common\CacheItem":private]=>
  bool(false)
}

Что это может быть? вроде все 4 аргумента передаются

**Comment by qunn** [comment]
У вас получается, что при вызове AtolClient формируется токен в кэш, но запрос токена из кэша  происходит перед AtolClient поэтому получается он пустой....если я не ошибаюсь, хотя могу

еще для дополнения, при использовании, ругается на PaymentObject и PaymentMethod, они не указаны в use:
use ItQuasar\AtolOnline\PaymentObject;
use ItQuasar\AtolOnline\PaymentMethod;

так же ошибка passwor и в вызове объекта в переменной $password указан, буквы не хватает))))

**Comment by qunn** [comment]
Проблема была в CacheItem, то что переменной $pool присваивается, оно и было имплементом CacheInterface

Было:
$pool = new FilesystemCachePool($filesystem);
$cache = $pool->getItem('atol');

Стало:
$cache = new FilesystemCachePool($filesystem);
